### ISSUE TITLE
Support for flow in GitHub

### ISSUE THREAD

**Issue by kivikakk** [area9innovation/flow9#202]
I've [started the process](https://github.com/github/linguist/pull/4515) for having flow recognised in GitHub -- this means that `.flow` files will be correctly recognised/categorised. We'll need to wait for a bunch more flow repos to appear first, but I thought getting the ball rolling can't hurt.

For syntax highlighting, [we currently need a TextMate-compatible grammar](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting). Is there one particularly suitable? I notice there's two different `Flow.tmLanguage` files in this repository.

**Comment by alstrup** [comment]
Thanks, sounds great! The Flow.tmLanguage in VS code should be fine.

**Comment by yegordovganich** [comment]
https://github.com/area9innovation/flow9/blob/master/resources/vscode/flow/syntaxes/Flow.tmLanguage

**Comment by alstrup** [comment]
We have one contributed repo here:
https://github.com/RusArtm/Simpulator

**Comment by alstrup** [comment]
We have one more here:
https://github.com/dmitry-vlasov/flow_metamath
@kivikakk How many do you think we need before we can make progress on this?

**Comment by kivikakk** [comment]
Per the checklist at github/linguist#4515, it should be used in "hundreds" of repos.

**Comment by alstrup** [comment]
One more here:
https://github.com/hey-sancho/flow_memorygame

**Comment by yegordovganich** [comment]
one more
https://github.com/ViktorKurach/mystore-demo
