### ISSUE TITLE
Win 10 QtByteRunner.exe issue

### ISSUE THREAD

**Issue by indiamcq** [area9innovation/flow9#207]
Not sure what goes first home page installation or windows.markdown instructions.
Did Windows.markdown first then on trying the step 4 on readme.md
```
Cd into the flow9 directory and compile and run the first program:

c:/flow9> flowcpp demos/demos.flow
```
I get a report from Win 10 that  QtByteRunner.exe is a 16bit program and won't run on 64bit.

**Comment by VsevolodZakharov** [comment]
Most likely you do not have Git LFS installed.

**Comment by dmitrys99** [comment]
Take a look to https://github.com/area9innovation/flow9#installation

**Comment by indiamcq** [comment]
I had installed Git LFS but my git clone did not work so I just downloaded the ZIP.
So I  installed Git LFS again,
Then I used Github Desktop to clone the repository. That asked me about LFS.
So I think it is good so far.
I just need to get Apache going before the next step I think.

Thanks for the help.

**Comment by VsevolodZakharov** [comment]
You don't need Apache if you are using flowcpp. It is Qt desktop app which compiles flow sources to the bytecode  and runs that.
Check flow/QtByteRunner/bin/QtByteRunner.exe - it should be a valid win exe ~ 1.7 M, not short LFS's hash file. If it does not LFS pull did not work.

**Comment by indiamcq** [comment]
I'll close this issue and start my next issue under a new topic.

Read a whole lot at night and mixed things up. Got it now, no Apache needed for flowcpp.

**Comment by dmitrys99** [comment]
Feel free to ask questions at telegram chat.

**Comment by indiamcq** [comment]
Sorry I don't install apps that want that many permissions. So I can't create an account and just use the web.
