### ISSUE TITLE
vscode support

### ISSUE THREAD

**Issue by fuzzthink** [area9innovation/flow9#209]
README says support in "Visual Code". Assuming you mean VSCode, it does not exists. Searched in VSCode extensions for "flow", everything is for flow-type. Searched for "flow9", no result.

**Comment by dmitrys99** [comment]
Please refer to [resources/vscode/flow](https://github.com/area9innovation/flow9/tree/master/resources/vscode/flow).

**Comment by fuzzthink** [comment]
Thanks, README should refer to it. https://github.com/area9innovation/flow9/pull/210

**Comment by yegordovganich** [comment]
#210 is merged
