### ISSUE TITLE
How to compile to nodejs?

### ISSUE THREAD

**Issue by fuzzthink** [area9innovation/flow9#211]
Trying to compile simple program to nodejs:

```
import runtime;

main() {
	println("hi");
}
```

`flow --js hi.js src/hi.flow`, `node hi.js`:
```
Platform.isAndroid = new EReg("android","i").match(window.navigator.userAgent);
                                                   ^

ReferenceError: window is not defined
```

Found `nodejs` option seems to exists in source.

`flow --nodejs hi.js src/hi.flow`

Got:
```
 Exception from eval: I could not make native Native.getKeysList: Could not find native getKeysList in Native. Recompile flowrunner.hxml, flowflash.hxml
```

No out.js produced.

**Comment by dmitrys99** [comment]
Tutorials for producing code for different platforms is being prepared and will be published soon.
Use following command instead:

`flowc1 hi.flow es6=hi.js nodejs=1`

One can also append `verbose=1` to see what happening during compilation.

`flowc1 hi.flow es6=hi.js nodejs=1 verbose=1`

Full list of commands are available via `flowc1 help=1`

`flow` is an original compiler,  written in haxe.
`flowc` is a current compiler, `flowc1` is the same as `flowc`, bootstrapped to Java for performance.

**Comment by fuzzthink** [comment]
Anyway to use `fs` (or anything else) from nodejs?   `fs/filesystem/readFileClient` says it's only for Qt. 

Also, anyway to import and use a js file?

**Comment by dmitrys99** [comment]
For reading file content use 
https://github.com/area9innovation/flow9/blob/415a7f9c6c9affa52aac79e3efc90a90b7b3dc11/lib/runtime.flow#L91

It is not possible to import foreign JS modules directly in Flow code.

Principally it is possible via creating native functions, but usually it must be proved we really can't avoid this.
