### ISSUE TITLE
Suggestion: Reduce sequential pipe forward chaining wrapper

### ISSUE THREAD

**Issue by fuzzthink** [area9innovation/flow9#212]
Instead of 
```
sumSqr = [0,1,2,3,4,5,6,7,8,9]
	|> (\l -> filter(l, \x->x%2==0))
	|> (\l -> map(l, \x->x*x))
	|> (\l -> fold(l, 0, \a, x -> a+x));
```

Most FP languages removes the need of the wrapper function:
```
sumSqr = [0,1,2,3,4,5,6,7,8,9]
	|> filter(\x->x%2==0)
	|> map(\x->x*x)
	|> fold(0, \a, x -> a+x)
```

**Comment by dmitrys99** [comment]
It is possible to omit function parameters if compiler supports curring.
Flow does not support curring, at least right now.

**Comment by alstrup** [comment]
As explained in this blog post (https://flow9.org/2019/04/26/why.html), it is unlikely that we will add implicit currying to flow.
It does mean the code is more verbose in examples like this, but the blog post also explains why we prefer it that way. In short: It is easier for beginners.

**Comment by fuzzthink** [comment]
Don't agree with reason, but thank you for pointing to it.
