### ISSUE TITLE
 unicode text support!

### ISSUE THREAD

**Issue by changloong** [area9innovation/flow9#275]
The `Hello user!` and `Schedule demo` show  unicode text as garbled!

![image](https://user-images.githubusercontent.com/15623/59971398-5f7b1880-95b6-11e9-808a-1a753bfbc3b4.png)

![image](https://user-images.githubusercontent.com/15623/59971408-88031280-95b6-11e9-8f8b-79ed6e033f13.png)

![image](https://user-images.githubusercontent.com/15623/59971411-99e4b580-95b6-11e9-9b95-bf6b6089ec41.png)

**Comment by changloong** [comment]
Android app has the same issue.

**Comment by Coolrunner86** [comment]
We do support unicode. Those symbols mean that font does not have such glyphs.

**Comment by changloong** [comment]
this is the issue come from default example, I guess it could fix easy by  load system font by default.

still good to know how to workaround this .

**Comment by Coolrunner86** [comment]
System fonts' support is in future plans.
You can add your own font to your app through FontConverter and fontprocessor tools. There will be some help text about this feature a bit later.

**Comment by VsevolodZakharov** [comment]
It is already there. See FlowRunnerWrapper.java::cbLoadSystemFont(). One needs to specify correct system font name in the *Text forms.

**Comment by Coolrunner86** [comment]
> It is already there. See FlowRunnerWrapper.java::cbLoadSystemFont(). One needs to specify correct system font name in the *Text forms.

Didn't know. What are the supported platforms?

**Comment by alstrup** [comment]
It works in all platforms if you just specify the font you want yourself. See also ui/fontmapping.flow which contains helpers to get a suitable font for various languages.
