### ISSUE TITLE
Method Jwts.parserBuilder() not found

### ISSUE THREAD

**Issue by advancedwebdeveloper** [area9innovation/flow9#729]
Hi.
I caught such an error:

> $ ./flowjava
> ~/Desktop/flow9/platforms/java ~/Desktop/flow9/bin
> com/area9innovation/flow/FlowJwt.java:29: error: cannot find symbol
> 			Jwts.parserBuilder().setSigningKey(getSecretKey(key)).build().parseClaimsJws(jwt);
> 			    ^
>   symbol:   method parserBuilder()
>   location: class Jwts
> com/area9innovation/flow/FlowJwt.java:60: error: cannot find symbol
> 				Claims jws = Jwts.parserBuilder().setSigningKey(getSecretKey(key)).build().parseClaimsJws(jwt).getBody();
> 				                 ^
>   symbol:   method parserBuilder()
>   location: class Jwts
> Note: javafx/com/area9innovation/flow/javafx/FxLoader.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 2 errors

I am using
> $ java -version
> openjdk version "11.0.9.1" 2020-11-04
> OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
> OpenJDK Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
> $ javac -version
> javac 11.0.9.1

Isn't that cause the source code references an abstract API, instead of an implementation?

Such a modification

> LIBS=$BASE_DIR/platforms/java/lib/java-websocket-1.5.1/*:$BASE_DIR/platforms/java/lib/jjwt-api-0.10.8/jjwt-impl-0.10.8.jar:$BASE_DIR/platforms/java/lib/jjwt-api-0.10.8/jjwt-jackson-0.10.8.jar:$BASE_DIR/platforms/java/lib/jjwt-api-0.10.8/jjwt-api-0.10.8.jar

did not help.

**Comment by Coolrunner86** [comment]
What do you want to achieve?

**Comment by Coolrunner86** [comment]
**flowjava** script invoked the old compiler which is kinda obsolete. To build .jar you should use **flowc1**.

**Comment by alstrup** [comment]
In other words, try "flowc1 sandbox/hello.flow jar=hello.jar".

**Comment by advancedwebdeveloper** [comment]
OK,
so this worked on rv64gc:

> $./flowc1 sandbox/hello.flow jar=hello.jar
> Flow compiler (3rd generation)
> 
> 
> done in 1975.82s
>
