### ISSUE TITLE
Telegram chat link in README has expired

### ISSUE THREAD

**Issue by Umbrien** [area9innovation/flow9#730]
I've tried to join the chat in Telegram, but it says that this link has expired.

**Comment by Coolrunner86** [comment]
Probably not so many people wanted to join, and it was abandoned. You may ask you questions here.

**Comment by advancedwebdeveloper** [comment]
Apparently you can consider moving to Slack

**Comment by Coolrunner86** [comment]
We have almost no community. So I guess there is no sense to have any chats. You may receive support here any time.

**Comment by alstrup** [comment]
We moved to discord: https://discord.gg/9gGJu6KU

**Comment by Sainan** [comment]
That Discord link is now also expired. 😄
